/* Shared by the browser, Tencent MariaDB and the legacy Firebase route.
 * Never add a text input to this allowlist. New measurements require review.
 */
(function (root) {
    const agents = Object.freeze({
        'lesson-design':'教学设计助手', 'courseware-outline':'课件大纲生成', 'micro-script':'微课脚本撰写',
        'lesson-hook':'情境导入设计', socratic:'苏格拉底助手', 'layered-q':'分层提问设计',
        'concept-explainer':'概念解释器', 'class-activity':'课堂活动设计', 'quiz-gen':'智能出题',
        'homework-grader':'作业批改助手', 'essay-review':'作文评改', 'exam-paper':'单元组卷',
        'error-diagnosis':'错题诊断', 'parent-comm':'家校沟通助手', 'student-comment':'学生评语生成',
        'class-meeting':'主题班会设计', 'heart-talk':'学生谈心顾问', 'teaching-reflection':'教学反思助手',
        'lesson-observe':'听评课助手'
    });
    const cases = Object.freeze({
        'poem-image':'古诗意境导入图', 'science-video':'科学实验三镜头短视频',
        'english-scene':'英语情景对话动画', 'math-motion':'数学概念动效脚本',
        'class-poster':'班会主题海报', 'audio-opening':'校园科技节开场音乐',
        'digital-human':'家长会说明视频', 'history-image':'历史情境观察图'
    });
    const pages = new Set(['index','agents','workspace','multimodal','media-player','classroom-tools',
        'tools','prompts','paths','articles','article','resources','news','offline']);
    const enums = {
        agentType:['form','chat'], category:['备课设计','课堂教学','作业评价','班级家校','教师发展'],
        status:['complete','reviewed','needs_revision','draft'],
        reviewStatus:['reviewed','needs_revision','draft'],
        reason:['usable','generic','level_mismatch','facts_check','hard_to_apply'],
        source:['agent_form','agent_chat','workflow'], workType:['draft','chat'],
        outcome:['accepted','dismissed','unknown'], platform:['ios','safari','other'],
        task:['lesson-design','quiz-gen','homework-grader','class-activity'],
        from:Object.keys(agents), type:['image','video','courseware','audio','avatar'],
        subject:['语文','科学','英语','数学','班主任','活动','家校','历史'], level:['入门','进阶','高级']
    };
    const fields = {
        page_view:[], agent_open:['agentType','category'], agent_run:['agentType','durationMs','hasProject'],
        generation_failed:['durationMs'], draft_restored:[], project_saved:['hasSubject','hasGrade'],
        teacher_reviewed:['status','reviseCount'], result_feedback:['reason'], workflow_continue:['from'],
        workbook_view:['workCount'], workbook_open:['workType'], workbook_save:['source','reviewed','reviewStatus'],
        pwa_task_launcher_opened:[], pwa_task_started:['task'], pwa_install_dismissed:[],
        pwa_install_choice:['outcome'], pwa_install_help_opened:['platform'], pwa_update_applied:[],
        pwa_update_deferred:[], pwa_installed:[], multimodal_case_open:['type','subject','level'],
        multimodal_video_open:['type','subject'], multimodal_audio_play:['type','subject']
    };
    const booleans = new Set(['hasProject','hasSubject','hasGrade','reviewed']);
    const maximums = { durationMs:600000, reviseCount:4, workCount:1000000 };
    const features = new Set(['site','agents','workspace','multimodal','classroom','tools','prompts','paths','articles','resources','news']);
    // Accept only identifiers generated by this tracker, never arbitrary text.
    function randomId(value, prefix) {
        return typeof value === 'string' && new RegExp(`^${prefix}_(?:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}|[a-z0-9]{8,12}_[a-z0-9]{1,8})$`, 'i').test(value) ? value : '';
    }
    function normalize(raw = {}) {
        if (!raw || !Object.hasOwn(fields, raw.action)) throw Object.assign(new Error('未知统计事件'), { statusCode:400 });
        const action = raw.action;
        const meta = {};
        const input = raw.meta && typeof raw.meta === 'object' ? raw.meta : {};
        for (const key of fields[action]) {
            const value = input[key];
            if (enums[key]?.includes(value)) meta[key] = value;
            else if (booleans.has(key) && typeof value === 'boolean') meta[key] = value;
            else if (Object.hasOwn(maximums,key) && Number.isInteger(value) && value >= 0 && value <= maximums[key]) meta[key] = value;
        }
        const slug = typeof raw.path === 'string' ? raw.path.split(/[?#]/)[0].replace(/^\/+|\/+$/g,'').replace(/\.html$/,'') || 'index' : '';
        const catalog = action.startsWith('multimodal_') ? cases : agents;
        const targetId = typeof raw.targetId === 'string' && Object.hasOwn(catalog,raw.targetId) ? raw.targetId : '';
        return {
            action, feature:features.has(raw.feature) ? raw.feature : 'site',
            visitorId:randomId(raw.visitorId,'v'), sessionId:randomId(raw.sessionId,'s'),
            path:pages.has(slug) ? (slug === 'index' ? '/' : `/${slug}`) : '',
            targetId, targetName:targetId ? catalog[targetId] : '', meta
        };
    }
    root.AnalyticsPolicy = Object.freeze({ normalize, agents, cases });
})(globalThis);
